In [1]:
import numpy as np

# 1. Datatypes & Attributes

In [3]:
# NumPy's main datatype is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [7]:
a2 = np.array([[1, 2.0, 3.3],
             [4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],
                [4, 5, 6]],
            [[7, 8, 9],
             [10, 11, 12]],
            [[13, 14, 15],
            [16, 17, 18]]])

In [8]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [9]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [10]:
a1.shape

(3,)

In [11]:
a2.shape

(2, 3)

In [12]:
a3.shape

(3, 2, 3)

In [13]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [14]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [15]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [16]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [18]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [17]:
# Create a DataFrame from NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

In [20]:
a4 = np.array([[100, 300, 600],
                 [-200, -400, -500]])

In [21]:
a4

array([[ 100,  300,  600],
       [-200, -400, -500]])

In [23]:
df2 = pd.DataFrame(a4)
df2

0    1    2
0  100  300  600
1 -200 -400 -500

# 2. Creating arrays

In [26]:
sample_array = np.array([10, 20, 30])
sample_array

array([10, 20, 30])

In [28]:
sample_array.dtype

dtype('int64')

In [29]:
ones = np.ones((2, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [30]:
ones.dtype

dtype('float64')

In [31]:
type(ones)

numpy.ndarray

In [33]:
zeros = np.zeros((2, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [35]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [37]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[4, 4, 3, 4, 2],
       [9, 6, 2, 6, 7],
       [5, 7, 7, 2, 0]])

In [38]:
random_array.size

15

In [39]:
random_array.shape

(3, 5)

In [41]:
random_array_2 = np.random.random((5,3))
random_array_2

array([[0.6738801 , 0.74185627, 0.63182597],
       [0.87985717, 0.0751603 , 0.25195785],
       [0.32667732, 0.20187023, 0.08929705],
       [0.21077361, 0.9721349 , 0.43317288],
       [0.15927657, 0.8343494 , 0.02381648]])

In [42]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.06731111, 0.19196405, 0.49729105],
       [0.19230403, 0.53080072, 0.56099345],
       [0.83775201, 0.68443157, 0.81150806],
       [0.568133  , 0.17647416, 0.0907248 ],
       [0.02697903, 0.83617927, 0.27941112]])

In [45]:
random_array_4 = np.random.randint(1, 1000, size=(10, 5))
random_array_4

array([[ 69,  37, 909, 860, 308],
       [106, 801, 610, 460, 249],
       [617, 139,  92, 567, 369],
       [497, 883, 866, 515, 829],
       [655, 808, 394, 300, 415],
       [848, 165, 362, 483, 964],
       [943, 598, 944, 638, 162],
       [407, 465, 547, 896, 781],
       [829, 206, 975, 850, 527],
       [693, 462, 302, 761, 652]])

In [47]:
df3 = pd.DataFrame(random_array_4)
df3

0    1    2    3    4
0   69   37  909  860  308
1  106  801  610  460  249
2  617  139   92  567  369
3  497  883  866  515  829
4  655  808  394  300  415
5  848  165  362  483  964
6  943  598  944  638  162
7  407  465  547  896  781
8  829  206  975  850  527
9  693  462  302  761  652

In [48]:
random_array_4.size

50

In [49]:
random_array_4.shape

(10, 5)

In [51]:
random_array_5 = np.random.random(size=(5, 10))
random_array_5

array([[0.01912829, 0.85924293, 0.05544471, 0.1583418 , 0.95367443,
        0.35592986, 0.58590284, 0.16769068, 0.99149455, 0.0788299 ],
       [0.54197488, 0.21827082, 0.68329231, 0.04193458, 0.61095686,
        0.08882037, 0.90942711, 0.83971662, 0.48678511, 0.49124605],
       [0.13897462, 0.45193364, 0.33910085, 0.08318079, 0.3034872 ,
        0.11883706, 0.24017176, 0.28912538, 0.46633524, 0.89801844],
       [0.1833816 , 0.76085778, 0.22518617, 0.03517732, 0.64005686,
        0.63575768, 0.15898058, 0.41275687, 0.26835702, 0.15639911],
       [0.15131983, 0.94065558, 0.52231912, 0.06883862, 0.33230421,
        0.91083129, 0.46801344, 0.79269015, 0.42029944, 0.84627583]])

In [53]:
df4 = pd.DataFrame(random_array_5)
df4

0         1         2         3         4         5         6  \
0  0.019128  0.859243  0.055445  0.158342  0.953674  0.355930  0.585903   
1  0.541975  0.218271  0.683292  0.041935  0.610957  0.088820  0.909427   
2  0.138975  0.451934  0.339101  0.083181  0.303487  0.118837  0.240172   
3  0.183382  0.760858  0.225186  0.035177  0.640057  0.635758  0.158981   
4  0.151320  0.940656  0.522319  0.068839  0.332304  0.910831  0.468013   

          7         8         9  
0  0.167691  0.991495  0.078830  
1  0.839717  0.486785  0.491246  
2  0.289125  0.466335  0.898018  
3  0.412757  0.268357  0.156399  
4  0.792690  0.420299  0.846276

In [56]:
random_array_6 = np.random.rand(5,5)
random_array_6

array([[0.50466308, 0.94516662, 0.85277205, 0.03495847, 0.32568643],
       [0.05997924, 0.03421293, 0.60444629, 0.15932892, 0.6394312 ],
       [0.00924751, 0.64519939, 0.48025824, 0.81138427, 0.87068626],
       [0.85592342, 0.77682312, 0.07502446, 0.10305399, 0.75881192],
       [0.92685303, 0.65932762, 0.12776474, 0.74924977, 0.46555528]])

In [58]:
range_array_2 = np.arange(0, 100, 5)
range_array_2

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [64]:
# Pseudo-random numbers
np.random.seed(seed=0)
random_array_7 = np.random.randint(10, size=(5, 3))
random_array_7

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [72]:
np.random.seed(seed=33)
random_array_8 = np.random.random((5,3))
random_array_8

array([[0.24851013, 0.44997542, 0.4109408 ],
       [0.26029969, 0.87039569, 0.18503993],
       [0.01966143, 0.95325203, 0.6804508 ],
       [0.48658813, 0.96502682, 0.39339874],
       [0.07955757, 0.35140742, 0.16363516]])

In [77]:
np.random.seed(seed=33)
random_array_8 = np.random.random((5,3))
random_array_8

array([[0.24851013, 0.44997542, 0.4109408 ],
       [0.26029969, 0.87039569, 0.18503993],
       [0.01966143, 0.95325203, 0.6804508 ],
       [0.48658813, 0.96502682, 0.39339874],
       [0.07955757, 0.35140742, 0.16363516]])

# 3. Viewing arrays & matrices

In [78]:
np.unique(random_array_7)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
a1

array([1, 2, 3])

In [80]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [81]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [82]:
a1[0]

1

In [83]:
a2[0]

array([1. , 2. , 3.3])

In [84]:
a3.shape

(3, 2, 3)

In [85]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [86]:
a2[1]

array([4. , 5. , 6.5])

In [93]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[ 7,  8],
        [10, 11]]])

In [95]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))
a4

array([[[[0, 6, 6, 9, 3],
         [3, 7, 2, 7, 2],
         [2, 9, 0, 4, 1],
         [3, 2, 9, 1, 0]],

        [[2, 9, 8, 2, 1],
         [7, 6, 7, 7, 0],
         [4, 8, 2, 4, 7],
         [6, 9, 5, 5, 2]],

        [[0, 1, 0, 9, 6],
         [4, 0, 2, 3, 5],
         [1, 4, 8, 6, 9],
         [3, 3, 9, 8, 9]]],


       [[[6, 7, 2, 4, 7],
         [4, 0, 8, 4, 6],
         [7, 0, 1, 5, 1],
         [7, 0, 2, 2, 0]],

        [[4, 2, 6, 6, 4],
         [3, 9, 2, 9, 5],
         [1, 1, 8, 7, 9],
         [2, 0, 7, 2, 0]],

        [[4, 2, 0, 4, 6],
         [2, 0, 4, 8, 6],
         [8, 9, 0, 1, 9],
         [8, 5, 2, 6, 1]]]])

In [96]:
# To understand shape start from the outermost array from right
# 5 elements in a row
# 4 rows
# 3 sets or arrays
# 2 groups
a4.shape

(2, 3, 4, 5)

In [97]:
a4.ndim

4

In [100]:
# Get the first 3 numbers of the innermost array ie. each row
# Slice first three dimensions ie. (2, 3, 4) not 5
# Slice all of dimension 1, all of 2, all of 3, but only up to first three numbers of dimension 4
a4[:, :, :, :3 ]

array([[[[0, 6, 6],
         [3, 7, 2],
         [2, 9, 0],
         [3, 2, 9]],

        [[2, 9, 8],
         [7, 6, 7],
         [4, 8, 2],
         [6, 9, 5]],

        [[0, 1, 0],
         [4, 0, 2],
         [1, 4, 8],
         [3, 3, 9]]],


       [[[6, 7, 2],
         [4, 0, 8],
         [7, 0, 1],
         [7, 0, 2]],

        [[4, 2, 6],
         [3, 9, 2],
         [1, 1, 8],
         [2, 0, 7]],

        [[4, 2, 0],
         [2, 0, 4],
         [8, 9, 0],
         [8, 5, 2]]]])